import 'bootstrap/dist/css/bootstrap.css';
import NavbarC from './components/NavbarC';
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import Home from './pages/Home';
import Patterns from './pages/Patterns';
import Guides from './pages/Guides';
import Share from './pages/Share';
import Pattern from './pages/Pattern'
import FAQ from './pages/FAQ';

const patternData = [
  {
    id: 1,
    title: "Peter the Penguin",
    type: "Animal",
    difficulty: "Easy",
    sewing: "Low",
    length: "1 hour",
    yarn: "Jumbo (7)",
    size: "Small", 
    image: "/images/penguin.png",
    tools: [
      "<b>Hook:</b> 6.5mm and 8mm", 
      "<b>Yarn:</b> Any colour (C), white (W), yellow (Y)",
      "<b>Safety Eyes:</b> 14mm",
      "<b>Stuffing</b>",
      "<b>Stitch Markers</b>",
      "<b>Scissors</b>",
      "<b>Sewing Needle</b>"
    ],
    instructions: [
      "<b>Body</b>",
      "Start with colour (C)",
      "Use 8mm hook",
      "<b>R1:</b> 8sc in a MR (8)",
      "<b>R2:</b> 8inc (16)",
      "<b>R3:</b> ( sc, inc ) x 8 (24)",
      "<b>R4:</b> C( 4sc ), W( 2sc ), C( 2sc ), W( 2sc ), C( 14sc ) (24)",
      "<b>R5-8:</b> C( 3sc ), W( 8sc ), C( 13sc ) (24)",
      "Secure safety eyes between R6 and R7, 3 stitches in between",
      "<b>R9:</b> C( 2sc, dec ), W( 2sc, dec, 2sc ), C( dec, ( 2sc, dec ) x 3 ) (18)",
      "Colour (C) only from now on",
      "<b>R10:</b> ( sc, dec ) x 6 (12)",
      "<b>R11:</b> 6dec (6)",
      "<br />",
      "<b>Wings</b>",
      "Start with colour (C)",
      "Use 8mm hook",
      "<b>R1:</b> Ch4",
      "<b>R2:</b> 3sc",
      "<b>R3:</b> Ch1, sc, slst",
      "Sew on R7",
      "<br />",
      "<b>Feet</b>",
      "Start with yellow (Y)",
      "Use 6.5mm hook",
      "<b>R1:</b> 6sc in a MR",
      "<br />",
      "<b>Beak</b>",
      "Embroider with yellow (Y)",
      "<br />",
      "<b>Enjoy your new penguin!</b>"
    ]
  },
  {
    id: 2,
    title: "Star Coin",
    type: "Object",
    difficulty: "Medium",
    sewing: "Medium",
    length: "1 hour",
    yarn: "Medium (4)",
    size: "Small", 
    image: "/images/coin.png",
    tools: [
      "<b>Hook:</b> 3.5mm", 
      "<b>Yarn:</b> Yellow and Gold",
      "<b>Stitch Markers</b>",
      "<b>Scissors</b>",
      "<b>Sewing Needle</b>"
    ],
    instructions: [
      "<b>Coin</b> (make 2)",
      "Start with yellow yarn",
      "* means repeat that stitch until the end of the round",
      "() means work in the same stitch",
      "<b>R1:</b> In a magic ring, sc 5, rev slst, ch 1 (5)",
      "<b>R2:</b> sc inc*, rev slst, ch 1 (10)",
      "<b>R3:</b> sc inc, sc*, rev slst, ch 1 (15)",
      "<b>R4:</b> [sc, ch 4, hdc in second ch, dc, tr, sk 2]x5, rev slst (5 star points)",
      "Finish off",
      "Continue with gold yarn",
      "<b>R5:</b> sk 4, bl all [sc, hdc, dc, tr 3, dc, hdc]x5, rev slst (40)",
      "Continue with yellow yarn. Ch2 to start.",
      "<b>R5:</b> R1: dc 3, dc inc* (50)",
      "Finish off. Leave an approx 36in. tail on the first coin. Then sew the two coins together.",
      "<br>",
      "<b>Enjoy your new star coin!</b>"
    ]
  },
  {
    id: 3,
    title: "Dangling Curly Plant",
    type: "Plant",
    difficulty: "Easy",
    sewing: "Medium",
    length: "2 hours",
    yarn: "Bulky (5)",
    size: "Medium", 
    image: "/images/plant.png",
    tools: [
      "<b>Hook:</b> 5.5mm", 
      "<b>Yarn:</b> Green and Brown",
      "<b>Stuffing</b>",
      "<b>Stitch Markers</b>",
      "<b>Scissors</b>",
      "<b>Sewing Needle</b>"
    ],
    instructions: [
      "<b>Soil Pot:</b>",
      "Start with brown yarn",
      "<b>R1:</b> 6sc in a magic ring (6)",
      "<b>R2:</b> 6inc (12)",
      "<b>R3:</b> (sc, inc)x6 (18)",
      "<b>R4:</b> (2sc, inc)x6 (24)",
      "<b>R5-9:</b> 24sc (24 for 5 rounds)",
      "<b>R10:</b> (4sc, dec)x4 (20)",
      "<b>R11:</b> 20sc (20)",
      "Slip stitch, fasten off and leave a long tail for sewing. Do not stuff yet.",
      "<br />",
      "<b>Curly Leaves:</b> (make 10 or as many as you want)",
      "Start with green yarn",
      "<b>R1:</b> Chain number for desired length and leave 4in tail for attaching to the soil",
      "<b>R2:</b> 3sc in the 2nd chain fom your hook and 3sc in each chain after until the end of the chain",
      "The curl will start to form, you may need to use your fingers to twist it into shape",
      "Finish off with about a 4in tail for attaching to the soil",
      "Repeat pattern for Curly Leaves with different starting lengths until you have your desired amount.",
      "Sew all of the leaves onto the soil pot using both tail ends of each leaf and secure with a knot inside the pot",
      "Stuf the soil pot, fasten off, and sew closed.",
      "<br>",
      "<b>Display your new dangling curly plant!</b>"
    ]
  },
  {
    id: 4,
    title: "Loaf Cat",
    type: "Animal",
    difficulty: "Easy",
    sewing: "Low",
    length: "3 hours",
    yarn: "Super Bulky (6)",
    size: "Medium", 
    image: "/images/loafcat.png",
    tools: [
      "<b>Hook:</b> 6.5mm", 
      "<b>Yarn:</b> Any Colour and Black",
      "<b>Safety Eyes:</b> 14mm",
      "<b>Stuffing</b>",
      "<b>Stitch Markers</b>",
      "<b>Scissors</b>",
      "<b>Sewing Needle</b>"
    ],
    instructions: [
      "<b>Body</b>",
      "Start with Colour",
      "<b>R1:</b> 8sc in a magic ring (8)",
      "<b>R2:</b> 8inc (16)",
      "<b>R3:</b> (sc, inc)x8 (24)",
      "<b>R4:</b> (2sc, inc)x8 (32)",
      "<b>R5:</b> (3sc, inc)x8 (40)",
      "<b>R6:</b> 17sc, flo sc, working in the flo of the next stitch (dc, ch 1, dc), flo sc, 4sc, flo sc, working in the flo of the next stitch (dc, ch 1, dc), flo sc, 13sc (38sc and 2 ears)",
      "<b>R7:</b> 17sc, 1 sc in each of the 3 back loops behind the ear, 4sc, 1 sc in each of the 3 back loops behind the ear, 13sc (40)",
      "<b>R8:</b> 40sc (40)",
      "<b>R9:</b> bobble st, 4sc, bobble st, sc around until you reach your first foot (38sc, 2 bobbles)",
      "Attach safety eyes between rows 3 and 4",
      "<b>R10-15:</b> 40sc (40 for 6 rows)",
      "<b>R16:</b> bobble st, 4sc, bobble st, sc around until you reach your first foot (38sc, 2 bobbles)",
      "<b>R17:</b> 40sc (40)",
      "<b>R18:</b> (3sc, dec)x8 (32)",
      "Begin stuffing your plushie",
      "<b>R19:</b> (2sc, dec)x8 (24)",
      "<b>R20:</b> (sc, dec) (16)",
      "<b>R21:</b> 8dec (8)",
      "Finish stuffing, sew the end closed and embroider the whiskers and nose on using the black yarn",
      "<br />",
      "<b>Tail</b>",
      "Start with Colour",
      "<b>R1:</b> 7sc in a magic ring (7)",
      "<b>R2-5:</b> 7sc (7 for 4 rounds)",
      "Fasten off and leave a long tail for sewing. Sew the tail onto R17 of the body.",
      "<br>",
      "<b>Show off your new adorable loaf cat!</b>"
    ]
  },
  {
    id: 5,
    title: "Tulip Pillow",
    type: "Object",
    difficulty: "Easy",
    sewing: "None",
    length: "4 hours",
    yarn: "Jumbo (7)",
    size: "Large", 
    image: "/images/tulippillow.png",
    tools: [
      "<b>Hook:</b> 8mm", 
      "<b>Yarn:</b> Yellow and Green",
      "<b>Stuffing</b>",
      "<b>Stitch Markers</b>",
      "<b>Scissors</b>",
      "<b>Sewing Needle</b>"
    ],
    instructions: [
      "<b>Leaf</b> (make 2)",
      "Start with Green",
      "<b>R1:</b> 5sc in a magic ring (5)",
      "<b>R2:</b> sc around (5)",
      "<b>R3:</b> 5inc (10)",
      "<b>R4-6:</b> sc around for 3 rounds (10)",
      "<b>R7:</b> (sc,inc)x5 (15)",
      "<b>R8:</b> sc around (15)",
      "<b>R9:</b> (2sc,inc)x5 (20)",
      "Stuff petals",
      "<b>R10:</b> sc around (20)",
      "<b>R11:</b> (2sc,dec)x5 (15)",
      "<b>R12:</b> (sc,dec)x5 (10)",
      "Fasten off, weave in the tail",
      "<br>",
      "<b>Tulip</b>",
      "<b>In yellow</b>",
      "<b>Make 3 of steps 1-5</b>",
      "<b>R1:</b> 6 sc in a magic ring (6)",
      "<b>R2:</b> inc x 6 (12)",
      "<b>R3:</b> (sc, inc) x 6 (18)",
      "<b>R4-5:</b> sc around for 2 rounds (18)",
      "Fo on the first two bumps and leave your hook on the third",
      "Now we will crochet the 3 bumps together to start our flower",
      "<b>R6:</b> With your 3rd bump still on the hook, do a slst onto any stitch on the 2nd bump (photo #1). Do 8 sc on the 2nd bump, do a slst on the 1st bump to attach it, do 17 sc on the 1st bump, do 9 sc on the 2nd bump & 18 sc on the 3rd bump (54)",
      "There will be a small hole between the bumps which you will stitch closed later, but for now just continue to crochet until instructed to tie it closed.",
      "<b>R7-14:</b> sc around for 8 rounds (54)",
      "<b>R15:</b> (7 sc, dec) x 6 (48)",
      "<b>R16-18:</b> sc around for 3 rounds (48)",
      "<b>R19:</b> (6 sc, dec) x 6 (42)",
      "<b>R20-21:</b> sc around for 2 rounds (42)",
      "<b>R22:</b> (5 sc, dec) x 6 (36)",
      "<b>R23:</b> (4 sc, dec) x 6 (30)",
      "Stuff flower (be careful not to overstuff as you want to be able to lay on the pillow)",
      "<b>R24:</b> (3 sc, dec) x 6 (24)",
      "<b>R25:</b> (2 sc, dec) x 6 (18)",
      "Change color to green",
      "<b>R26-39:</b> sc around for 14 rounds (18)",
      "Stuff the stem as you go",
      "We will attach the leaves in this next round using the no-sew method",
      "<b>R40:</b> sc, 5 sc to attach the 1st leaf to the stem, 4 sc, 5 sc to attach the 2nd leaf to the stem, 3 sc (18)",
      "<b>R41:</b> (sc, dec) x 6 (12)",
      "<b>R42:</b> dec x 6 to close",
      "Fo, weave in tail",
      "<br>",
      "<b>Leaf</b> (make 2)",
      "Start with green",
      "<b>R1:</b> 5 sc in a magic ring (5)",
      "<b>R2:</b> sc around (5)",
      "<b>R3:</b> 5 inc (10)",
      "<b>R4-6:</b> sc around for 3 rounds (10)",
      "<b>R7:</b> (sc, inc) x 5 (15)",
      "<b>R8:</b> sc around (15)",
      "<b>R9:</b> (2 sc, inc) x 5 (20)",
      "Stuff petals",
      "<b>R10:</b> sc around (20)",
      "<b>R11:</b> (2 sc, dec) x 5 (15)",
      "<b>R12:</b> (sc, dec) x 5 (10)",
      "Fasten off, weave in the tail",
      "<br>",
      "<b>Show off your new tulip pillow!</b>"
    ]
  },
  {
    id: 6,
    title: "Toby the Tarbosaurus",
    type: "Animal",
    difficulty: "Hard",
    sewing: "High",
    length: "5+ hours",
    yarn: "Super Bulky (6)",
    size: "Medium", 
    image: "/images/tarbosaurus.png",
    tools: [
      "<b>Hook:</b> 6.5mm", 
      "<b>Yarn:</b> Pink, Purple, White",
      "<b>Safety Eyes:</b> 10mm",
      "<b>Stuffing</b>",
      "<b>Stitch Markers</b>",
      "<b>Scissors</b>",
      "<b>Sewing Needle</b>"
    ],
    instructions: [
      "<b>Body</b>",
      "Start with Purple",
      "<b>R1:</b> Begin with 6 sc in a magic ring. (6 sts)",
      "<b>R2:</b> 2 sc in each st around. (12 sts)",
      "<b>R3:</b> *2 sc in next st, 1 sc in next st. Repeat from * around. (18 sts)",
      "<b>R4:</b> *2 sc in next st, 1 sc in each of the next 2 sts. Repeat from * around. (24 sts)",
      "<b>R5:</b> *2 sc in next st, 1 sc in each of the next 3 sts. Repeat from * around. (30 sts)",
      "<b>R6-12:</b> 1 sc in each st around. (30 sts)",
      "<b>R13:</b> *sc2tog, 1 sc in each of the next 3 sts. Repeat from * around. (24 sts)",
      "<b>R14-18:</b> 1 sc in each st around. (24 sts)",
      "<b>R19:</b> *sc2tog, 1 sc in each of the next 2 sts. Repeat from * around. (18 sts)",
      "<b>R20:</b> 1 sc in each st around. (18 sts)",
      "Cut yarn, leaving long strand for sewing. Fasten off.",
      "Fill with stuffing.",
      "<br>",
      "<b>Head</b>",
      "Start with Purple",
      "<b>R1:</b> Begin with 6 sc in a magic ring. (6 sts)",
      "<b>R2:</b> 2 sc in each st around. (12 sts)",
      "<b>R3:</b> *2 sc in next st, 1 sc in next st. Repeat from * around. (18 sts)",
      "<b>R4-6:</b> 1 sc in each st around. (18 sts)",
      "<b>R7:</b> *2 sc in next st, 1 sc in each of the next 2 sts. Repeat from * an additional 2 times. 1 sc in each of the next 9 sts around. (21 sts)",
      "<b>R8:</b> *2 sc in next st, 1 sc in each of the next 3 sts. Repeat from * an additional 2 times. 1 sc in each of the next 9 sts around. (24 sts)",
      "<b>R9:</b> *2 sc in next st, 1 sc in each of the next 4 sts. Repeat from * an additional 2 times. 1 sc in each of the next 9 sts around. (27 sts)",
      "<b>R10:</b> *2 sc in next st, 1 sc in each of the next 5 sts. Repeat from * an additional 2 times. 1 sc in each of the next 9 sts around. (30 sts)",
      "<b>R11:</b> *2 sc in next st, 1 sc in each of the next 4 sts. Repeat from * an additional 2 times. Add a st marker to the last worked st. **2 sc in next st, 1 sc in each of the next 4 sts. Repeat from ** an additional 2 times. (36 sts)",
      "The added st marker, and the st marker at the beginning of this round helps to indicate the front sides of the face. The first sequence of sts between the first and second st markers indicates the top of the head. The second sequence of sts between the second and first st markers indicates the bottom of the head. If using safety eyes, insert eyes between R8 and R9, with 7 sts between. You can now remove your second st marker.",
      "<b>R12-15:</b> 1 sc in each st around. (36 sts)",
      "<b>R16:</b> *sc2tog, 1 sc in each of the next 4 sts. Repeat from * around. (30 sts)",
      "<b>R17:</b> *sc2tog, 1 sc in each of the next 3 sts. Repeat from * around. (24 sts)",
      "<b>R18:</b> 1 sc in each st around. (24 sts)",
      "<b>R19:</b> *sc2tog, 1 sc in each of the next 2 sts. Repeat from * around. (18 sts)",
      "<b>R20:</b> *sc2tog, 1 sc in next st. Repeat from * around. (12 sts)",
      "Fill head with stuffing.",
      "<b>R21:</b> *sc2tog. Repeat from * around. (6 sts)",
      "Cut yarn, weave yarn in and out of remaining sts. Pull tight to close. Tie off and weave in ends.",
      "<br>",
      "<b>Legs (Make 2)</b>",
      "Using pink:",
      "<b>R1:</b> Begin with 6 sc in a magic ring. (6 sts)",
      "<b>R2:</b> 2 sc in each st around. (12 sts)",
      "<b>R3:</b> *2 sc in next st, 1 sc in next st. Repeat from * around. (18 sts)",
      "<b>R4:</b> *2 sc in next st, 1 sc in each of the next 2 sts. Repeat from * around. (24 sts)",
      "Using purple:",
      "<b>R5-6:</b> 1 sc in each st around. (24 sts)",
      "<b>R7:</b> *sc2tog, 1 sc in each of the next 2 sts. Repeat from * around. (18 sts)",
      "<b>R8-9:</b> 1 sc in each st around. (18 sts)",
      "<b>R10:</b> *sc2tog, 1 sc in each of the next 7 sts. Repeat from * around. (16 sts)",
      "<b>R11-15:</b> 1 sc in each st around. (16 sts)",
      "Fill with stuffing.",
      "<b>R16:</b> Fold the leg closed. Working through both sides, 1 sc in each st across, leaving 1 unworked st on each side.",
      "Cut yarn and fasten off.",
      "<br>",
      "<b>Arms (Make 2)</b>",
      "Using pink:",
      "<b>R1:</b> Begin with 6 sc in a magic ring. (6 sts)",
      "<b>R2:</b> 2 sc in each st around. (12 sts)",
      "<b>R3:</b> *2 sc in next st, 1 sc in next st. Repeat from * around. (18 sts)",
      "Using purple:",
      "<b>R4-5:</b> 1 sc in each st around. (18 sts)",
      "<b>R6:</b> *sc2tog, 1 sc in next st. Repeat from * around. (12 sts)",
      "<b>R7-11:</b> 1 sc in each st around. (12 sts)",
      "Fill with stuffing.",
      "<b>R12:</b> Fold the arm closed. Working through both sides, 1 sc in each st across, leaving 1 unworked st on each side. (5 sts)",
      "Cut yarn, leaving long strand for sewing. Fasten off.",
      "<br>",
      "<b>Tail</b>",
      "Using purple:",
      "<b>R1:</b> Begin with 4 sc in a magic ring. (4 sts)",
      "<b>R2:</b> 1 sc in each st around. (4 sts)",
      "<b>R3:</b> *2 sc in next st, 1 sc in next st. Repeat from * around. (6 sts)",
      "<b>R4:</b> 1 sc in each st around. (6 sts)",
      "<b>R5:</b> *2 sc in next st, 1 sc in next st. Repeat from * around. (9 sts)",
      "<b>R6-7:</b> 1 sc in each st around. (9 sts)",
      "<b>R8:</b> *2 sc in next st, 1 sc in each of the next 2 sts. Repeat from * around. (12 sts)",
      "<b>R9:</b> 1 sc in each st around. (12 sts)",
      "<b>R10:</b> *2 sc in next st, 1 sc in each of the next 3 sts. Repeat from * around. (15 sts)",
      "Cut yarn, leaving long strand for sewing. Fasten off.",
      "Fill with stuffing.",
      "<br>",
      "<b>Spikes (Make 7)</b>",
      "Using pink:",
      "<b>R1:</b> Begin with 6 sc in a magic ring. (6 sts)",
      "<b>R2:</b> *2 sc in next st, 1 sc in next st. Repeat from * around. (9 sts)",
      "<b>R3:</b> 1 sc in each st around. (9 sts)",
      "<b>R4:</b> Fold the spike closed. Working through both sides, 1 sc in each st across, leaving 1 unworked st at the beginning. (4 sts)",
      "Cut yarn, leaving long strand for sewing. Fasten off.",
      "<br>",
      "<b>Assembly and Finishing</b>",
      "Attach head to body so that the nose is facing straight out; attaching body to approximately R10-16 of the bottom of the head.",
      "Using purple, embroider nostrils over R2-3 of the nose, leaving about 3 sts between each.",
      "Attach legs over R4-5 of body, with each inside end of the legs touching in the middle.",
      "Attach arms over R12-18 on each side of the body, in line with the back of each leg. At the top of the arms, leave approximately 10 sts between each arm across the front of the body. At the bottom of the arms, leave approximately 14 sts between each arm across the front of the body.",
      "Using white, embroider 3 nails on each leg, over R3-5, leaving about 2 sts between each nail and embroider 3 nails on each arm, over R3-4, leaving about 2 sts between each nail.",
      "Attach tail over R4-8, on the back of the body.",
      "Beginning at the tip of the tail, and using pins to keep them even, arrange spikes in a line up the tail, back, and over the head, and sew them all on.",
      "<b>Show off your new adorable tarbosaurus!</b>"
    ]
  }
]

function App() {
  return (
    <Router>
      <NavbarC />
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/patterns" element={<Patterns patternData={patternData} />} />
        <Route path="/guides" element={<Guides />} />
        <Route path="/share" element={<Share />} />
        <Route path="/pattern/:id" element={<Pattern patternData={patternData} />} />
        <Route path="/FAQ" element={<FAQ />} />
      </Routes>
    </Router>
  );
}

export default App;
